name: persistent_login
description: "Flutter persistent login example"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
